apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGateway
metadata:
  name: gateway
spec:
  serviceAccount:
    name: acme-fitness-service-account
  api:
    serverUrl: http://acme-fitness.spring.animalrescue.online
    groupId: acme-fitness
    title: "ACME Fitness Gateway"
    description: "ACME Fitness application for Spring Cloud Gateway commercial product demos."
    documentation: "https://github.com/spring-cloud-services-samples/acme_fitness_demo/"
    version: "1.0.0-K8s"
    cors:
      allowedOrigins:
      - "http://api-portal.spring.animalrescue.online"
  observability:
    metrics:
      wavefront:
        enabled: true
    tracing:
      wavefront:
        enabled: true
    wavefront:
      secret: wavefront-secret
      application: acme-fitness-demo
      service: acme-gateway
  extensions:
    secretsProviders:
      - name: vault-provider
        vault:
          roleName: acme-fitness-role
    filters:
      apiKey:
        enabled: true
        secretsProviderName: vault-provider

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scg-ingress
spec:
  rules:
  - host: acme-fitness.spring.animalrescue.online
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gateway
            port:
              number: 80
