apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: users-route-config
spec:
  routes:
    - ssoEnabled: true
      uri: no://op
      predicates:
        - Path=/acme-login
        - Method=GET
      filters:
        - RedirectTo=302, /
      tags:
        - users
    - ssoEnabled: true
      uri: no://op
      predicates:
        - Path=/userinfo
        - Method=GET
      filters:
        - WhoAmI
        - SetResponseHeader=Cache-Control, no-store
      tags:
        - users
    - uri: no://op
      predicates:
        - Path=/verify-token
        - Method=POST
      ssoEnabled: true
      tags:
        - users
---
apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayMapping
metadata:
  name: users-routes
spec:
  gatewayRef:
    name: gateway
  routeConfigRef:
    name: users-route-config
